# Generated by Django 5.0.1 on 2024-01-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='category',
            field=models.IntegerField(choices=[(1, 'mobile'), (2, 'clothes'), (3, 'shoes')]),
        ),
    ]
