# Generated by Django 5.0.1 on 2024-02-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_carttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttable',
            name='order_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carttable',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
